### ISSUE TITLE
Start from scratch

### ISSUE THREAD

**Issue by V1TA5** [KSP-SpaceDock/SpaceDock#114]
im still thinking about if it would be good and doabble to start a branch that redos the whole site from scfratch implementing cdn support, getting rid of all that middleware, and use a white ver of d-mp.orgs design. and yes i would do it in php because thats what im best at but you can bring forward constructive arguments why lang X would be a better choice.

My choice would be: 
some sql db (mysql has a nifty new json datatype that enables some nice new possibilities for stored functions and such)

slim framework (fast, small, and does many things we need 
(maybe i even would go and try smphony for the first time)

twig template engine (we allready use it)

rachet / reacht (websockets insetead of most of the ajax stuff for more instant updates of the site)

php7 (if vailable for productive use)

discuss

**Comment by ThomasKerman** [comment]
I definitly support this, even though my PHP is... creepy :smiling_imp: 

I would definitly prefer something like C#, because it is fast, it has lots of libraries and you can bundle them all into one executable file (so not all this yadda yadda with deps). But I am open to everything. What languages do you know besides of PHP @V1TA5 ?

**Comment by GenPage** [comment]
As a big PHP dev, definitely would not be my first choice. There are more web-optimized languages out there. I vote we stick with Python or consider Ruby/NodeJS.

**Comment by V1TA5** [comment]
i would say it depens of the coding style and your dicipline. it would be an advantage and also my fear that more ppl could contribute but in php (as you sure know) its easy to produce bad code.

**Comment by FrikFry** [comment]
I would agree with @GenPage, I'd prefer Python, NodeJS, or Ruby.

**Comment by avivey** [comment]
I'll just put this here:
http://www.joelonsoftware.com/articles/fog0000000069.html

**Comment by V1TA5** [comment]
what makes ruby, python nodejs and so on the one to use.

whats the most popular lang to write webapps in?

the reason to rewrite the code is that the code wasnt written by any of us and with different goals in mind than we have today. i wouldnt want to rewrite it exactly but recreate the sites functions in a different way.

**Comment by ILM126** [comment]
Would a Laravel Framework well with this type of site? I'm still learning how to efficiently use Laravel framework, but I'm just leaving this idea here for discussion ^_^

**Comment by GenPage** [comment]
I'm voting for sticking with the current codebase. We do not need a complete rewrite from scratch. We have a base to work with. Let's optimize and refactor. Focus on new features and bug fixing.

**Comment by FrikFry** [comment]
@GenPage :+1:

**Comment by RockyTV** [comment]
> the reason to rewrite the code is that the code wasnt written by any of us and with different goals in mind than we have today.
I think this could be fixed by documenting each piece of code. Then we can have some sort of idea of what that piece does, and it would be so much easier to contribute because you wouldn't have to spend some minutes trying to figure out where/what is the method you need to change.

**Comment by jtac** [comment]
I would absolutely support this, CDN support is the breaking point of the whole thing in my opinion.

**Comment by V1TA5** [comment]
CDN will happen on a lower level. but my main reason is that i imagine it would be quite some work to enable to have "multigame" support in a single instance because you would need to add site/game ids to each portion of the code. (i realy want spacedock to be able to offer its services to other games than ksp too)

**Comment by jkoritzinsky** [comment]
If language changes are still on the table, I suggest C# or node.js. I might be biased because I've been wanting to help contribute and I know these platforms the best of the listed ones (excluding PHP, but I don't want to deal with that again if I can avoid it).

In any case, the code needs to be documented and refactored to be testable. Makes it much easier to add new features.

**Comment by EIREXE** [comment]
I don't believe a rewrite is a good idea at all, I believe we should focus on working from what we have, the main reason people usually start from scratch is licensing, and we don't have that issue.

**Comment by godarklight** [comment]
I'd also suggest sticking to what we have. Rewriting is a lot of work, and currently there is huge gains to be had in terms of resources by thumbnail generation, and looking into why the main page takes a second to generate currently (SirCmpwn mentioned the SQL lookups on the main page are a big performance hit, but I've not yet put timers around any methods yet)

**Comment by inigmatus** [comment]
I am also for this idea, as I am familiar with reading and debugging php code.

**Comment by EIREXE** [comment]
I just can't see the point.

**Comment by WASasquatch** [comment]
Dear lord please dont jump the NodeJs bandwagon. :( tried and true.

**Comment by HebaruSan** [comment]
- Multi-game is done and functional
- CDN support also exists unless I'm mistaken about what that means
- The talk of which languages are "fast" was misguided—SpaceDock was slow because its code was doing horrendously inefficient things like loading entire tables from the db, various operations without good db indexes, recalculating every mod's score and thumbnail to render mod lists, recompiling templates on every page load, etc., not because it uses Python and Flask. We've found those with #346's profiling and fixed them and it's fast now. Doing that sort of crap in Nodejs or C# would have been just as slow.

This isn't an issue that someone's going to sit down and work on, so let's close it.
