### ISSUE TITLE
[Feature] Rating system for Mods

### ISSUE THREAD

**Issue by tfischer4765** [KSP-SpaceDock/SpaceDock#123]
Doesn't everything have a five-star rating system these days? I think with the varying quality of mods, spacedock could really benefit from one of those.

Proposed components (just off the top of my head):
Graphics, functionality, completeness, game balance, version compatibility (a lot of nominally outdated mods work fine)

**Comment by ThaZeus** [comment]
This would be useful as a addition to the suggested in #101

**Comment by tfischer4765** [comment]
Out of curiosity, what does my suggestion have in common with #101?

**Comment by godarklight** [comment]
If we do add a rating system, I'd like this to be superficial and not affect rankings - All user input is bad, and downloads + followers should be a fairly good indicator for good mods ;)

**Comment by tfischer4765** [comment]
I need a compass for this conversation, why is all user input bad? Also, downloads + followers only goes so far, especially if you count total downloads and don't apply a moving window. Also, number of downloads only tells you how many people found the mod interesting, not how many actually liked it.

**Comment by Olympic1** [comment]
The way the rating system will work will be the same as on the forums.
* The mod is broken because the user installed it wrong, so he/she will give the lowest rating.
* The mod works very nice, so he/she will give it the highest rating.
* Then there will be some users that will give it a rating that lays between those.

This system will not be reliable as the downloads/followers count

**Comment by tfischer4765** [comment]
Seems to work fine for andoid apps on the play store though. The one-starers and the five-starers usually mostly cancel each other out. I'm not saying that this is a perfect system either. If I had one of those, I'd be a millionaire working for Google. I'm also not proposing to dump followers or downloads as a metric, by all means keep those.

Ok, let's add another layer of QA to the logic: if the user gives either the higest or lowest rating, he can't submit it without writing a comment.

**Comment by godarklight** [comment]
For anyone wondering, I think the technical implentation of this is usually along the lines of this:

1 star: -2
2 star: -1
3 star: 0
4 star: 1
5 star: 2

That way a crapton of 1 star ratings won't outrank a mod with a few 5 star ratings. But I'm still iffy on this - if one of the other devs wants to implement it they can, although I still think a sliding download count would be better.

(I had to change the most popular mods today to total downloads today, but it returns the same results anyway)

**Comment by GenPage** [comment]
We could always build a rating system that focus around functionality rather than "stars" or "upvotes"/"downvotes". Maybe a count of "Works Great", "Setup Difficulty", "Broken". 

This can bring in valuable user input related to the mod outside of its "popularity" via downloads/followers.

**Comment by tfischer4765** [comment]
@GenPage I think you are thinking along the same lines I am. Originally, my idea wasn't a simple five-star-slapon rating, but rather a differentiated system with five stars in several categories each (see original issue). Those could be collapsed into a summary star rating - or not, if that's not what you guys want. I'm not thinking so much in terms of "rating" and "ranking" but more along the lines of giving the user the option to write a review and rate some facets of the mod with a star rating. I think I mentioned, graphics, functionality, game balance, etc. 

Does that make my intention clearer?

**Comment by inigmatus** [comment]
@GenPage I think a mod status vote is awesome. Would also help with reporting broken mods over all.

**Comment by HebaruSan** [comment]
**Report broken mods on the forum or as a GitHub issue (or become a pull request hero!), where the author can see your comment, investigate your logs, catch user errors, and fix bugs.** Clicking a one star icon on SpaceDock may feel satisfying, but it won't accomplish anything other than making the mod look slightly worse to other users who bother to glance at the star rating.

> Doesn't everything have a five-star rating system these days?

No, I don't think that was the case even when this was submitted. Youtube ditched 5 star ratings in favor of thumb-up/down in **2009**, probably for many of the same reasons that were brought up here (users who care enough to click are highly likely to be biased in favor of 1 and 5 stars depending on whether their opinion is negative or positive).

Having _multiple_ components with 1–5 star ratings each sounds really busy—who has the time to look at or click all of those things?—as well as making it nearly impossible to summarize usefully. Should a mod with low "Graphics" ratings sort above or below a mod with low "Completeness" ratings?

And of course this idea has all the same problems that apply when people request the same thing for CKAN (see KSP-CKAN/CKAN#2093): Should downvotes from users on version X be visible to users on version Y? If a downvote is because of a temporary problem, how would they be cleared when that problem is fixed?

Let's not do this.
