### ISSUE TITLE
Dynamic loading javascript does not work on Edge

### ISSUE THREAD

**Issue by EIREXE** [KSP-SpaceDock/SpaceDock#149]
The javascript that dynamically loads the browse parts of the site does not work in microsoft edge.

**Comment by DasSkelett** [comment]
Edge changed a lot since this issue has been created and is now based on Chromium.
I've just tested browsing different pages on SpaceDock with Edge, and everything seemed to work fine, XHRequests get executed and load images & co. I don't think this is still a issue, but if it is, please let us know.
