### ISSUE TITLE
Suggestion: Sorting by compatible version

### ISSUE THREAD

**Issue by t3pfaffe** [KSP-SpaceDock/SpaceDock#174]
I was wondering about the implementation of a system that would allow people to sort mods by their current version (multiple versions at same time to stop the 1.1.x updates that dont break things getting in the way). Also some mod creators my not update their compatible version. To counter that a system where you could vote whether or not the mod works in the current version that starts again every time KSP is updated.

**Comment by HebaruSan** [comment]
Something similar was done in #287, but in the core mod scoring mechanism rather than a user-chosen sort. Mods that don't update now lose a percentage of their scores per later incompatible release. Checking the first several pages of the popular mods list, this seems to have solved the problem of old out of date mods cluttering the list.
