### ISSUE TITLE
Ability to update the file for a release

### ISSUE THREAD

**Issue by mwerle** [KSP-SpaceDock/SpaceDock#184]
It would be nice to be able to replace the file uploaded for a release (without re-notifying followers).

Use-case: Created a new release with a ZIP which contains some extraneous files (yes, shoddy release management, I know).  

Would like to replace the ZIP for a particular release with a new one without having to create a new release or notifying people again (no point to re-download for people who already have).

**Comment by allista** [comment]
I second this.

Cases where you've published something in error are plenty. E.g. I've just spent an hour fixing 4 releases where I've accidentally published dev versions of dlls.

The problem is: even if I delete the release, then republish with the same version but use different archive, the "new" release still points to the old archive.

So the simplest thing would suffice: update release archive on the server even if there's one with that name.

And the way GitHub handles this, namely, allowing to just add/remove files to the release -- would be perfect!

**Comment by HebaruSan** [comment]
> The problem is: even if I delete the release, then republish with the same version but use different archive, the "new" release still points to the old archive.

I think the appearance of that happening is an artifact of server-side caching. If you delete an existing release and re-create it with the same version number, the file is replaced on the server, but downloading it right away gives the original file. **But** downloading it hours later gives the new file. Whatever service is caching downloads does not know it has been replaced.

We see evidence of this with the CKAN bot, see https://github.com/KSP-CKAN/NetKAN#8055...

Timestamp | Event
:-- | :--
2020-07-21T08:01:46.243285+00:00 | [Original upload](https://github.com/KSP-CKAN/CKAN-meta/commit/f14d2d4081c7905eadfa40fceedcf0d6d2c0cb77#diff-48281f930deeca3aea4eb41647a25f0e)
2020-07-21T08:49:53.534665+00:00 | [Replacement upload](https://github.com/KSP-CKAN/CKAN-meta/commit/8d0d657856f081a30d7ba32df2e1353bc3e99291#diff-48281f930deeca3aea4eb41647a25f0e)
2020-07-21T09:13 | Latest download by CKAN, still the old file! (timestamp reported by techman83)
2020-07-22T13:13 | [New file retrieved after manual client cache purge](https://github.com/KSP-CKAN/CKAN-meta/commit/a77ba0c4762f1f8200fa1a271cbc971cd014533b#diff-48281f930deeca3aea4eb41647a25f0e)

Download URLs (the post-redirect ones, not pre-) may need a timestamp piece to force them to be unique regardless of mod author behavior.
