### ISSUE TITLE
Add ability to update or confirm 'Add to CKAN' button post-mod creation

### ISSUE THREAD

**Issue by DBooots** [KSP-SpaceDock/SpaceDock#190]
Description:
Right now, the one and only time the 'Add to CKAN' button appears is during the initial creation of the mod page. It would be good to be able to go back and either change the status or confirm you selected it. (Especially while https://github.com/KSP-SpaceDock/SpaceDock/issues/188 is open).

Reproduction Steps:
Upload a mod. 'Add to CKAN' button is not visible on either the 'Update Mod' or 'Edit Mod' screens.

Expected Behavior:
In either of those screens, I think the 'Add to CKAN' button should be there. If, due to back-end reasons, it cannot be changed after mod creation, I think it should still be there but greyed out if only to show status.

Environment: OS X/Firefox

**Comment by allista** [comment]
@V1TA5 do you agree with this?

**Comment by V1TA5** [comment]
Indication yes. The ability to switch ckan off: check with ckan if thats possible. enable ckan later: sure why not.

**Comment by HebaruSan** [comment]
> ability to switch ckan off: check with ckan if thats possible

I think it would be possible technically. We could have it submit a pull request to rename `NetKAN/identifier.netkan` to `NetKAN/identifier.frozen`, which is how we would do it manually.

I'm not sure it's a good idea, though. It's already possible to de-index a mod by asking on the forum thread or submitting an issue or PR or various other ways. De-indexing with one click might encourage "churn" where fickle authors go back and forth between indexed and not, wasting the time of metadata maintainers. (Not a fictional concern, at least one author has already done this a few times.)

**Comment by V1TA5** [comment]
We might want to include tooltips or a help icon with modal that tells you something along the lines of "if you enable ckan you cant disable it again"

**Comment by DasSkelett** [comment]
Related: from time to time gets automated indexing requests via this button that the CKAN team declines, be it because of dependencies that aren't indexed, OS-dependent mods which CKAN can't handle, for policy reasons or whatever.
It would be cool to be able to deactivate the CKAN badge again for these mods.

I thought about adding a webhook to [NetKAN-Infra](https://github.com/KSP-CKAN/NetKAN-Infra), with which SpaceDock can dynamically check whether a mod is indexed on CKAN, instead of relying on a once-set bool in the database.

However the netkan infrastructure isn't currently set up for being used by a website in production, see [this comment](https://github.com/KSP-CKAN/NetKAN-Infra/pull/177#issuecomment-636601511) by @techman83.

**Comment by HebaruSan** [comment]
The problem description does not seem to be correct, the checkbox is already present on the edit screen:

![image](https://user-images.githubusercontent.com/1559108/85444531-0989d980-b558-11ea-9eda-00a294b20261.png)

It does, however, disappear if it has been checked previously. Maybe that's causing confusion?

**Comment by DasSkelett** [comment]
Fixed in #337 

As an author you now can always see the status of the CKAN checkbox post-creation. You can't disable it again, except if the mod is still unpublished. Admins can disable the checkbox again if required in some cases, e.g. to reflect the real CKAN indexation state – note however that this simply changes SpaceDock's bool in the database, it does not send a de-indexation request whatsoever towards CKAN.
