### ISSUE TITLE
Unable to upload large files

### ISSUE THREAD

**Issue by Gameslinx** [KSP-SpaceDock/SpaceDock#250]
Description: I have a mod which is 1.02 GB. When uploading, the progress bar continuously gets to around 66% and stops during upload.

Reproduction Steps: Try to upload a large file. The mod i'm trying to upload is Beyond Home, which is available from this releases page: https://github.com/Gameslinx/BeyondHomePlanetMod/releases

Expected Behavior: Upload should complete

Environment (OS/Browser/Plugins/etc): Google chrome, Windows 10

**Comment by DasSkelett** [comment]
So I did re-test uploading big files now,this time with a 2GB file since 1GB files always worked fine.
And tadaa, it does indeed stop somewhere in the middle.
Looking at the console output, it seems to always cut the transmission when hitting exactly 15 minutes:
![grafik](https://user-images.githubusercontent.com/28812678/81870115-85662e80-9575-11ea-8856-abcc2c84b11c.png)

Also tested on alpha, this is from the Apache error.log:
```
[Wed May 13 21:51:13.188177 2020] [proxy_http:error] [pid 25131:tid 140431108876032] (70008)Partial results are valid but processing is incomplete: [client 10.150.1.9:39858] AH02609: read request body failed to 127.0.0.1:8004 (127.0.0.1) from 10.150.1.9 (), referer: https://alpha.spacedock.info/mod/3/Test%20download%20path/update
[Wed May 13 21:51:13.197056 2020] [proxy_http:error] [pid 25131:tid 140431108876032] [client 10.150.1.9:39858] AH01097: pass request body failed to 127.0.0.1:8004 (127.0.0.1) from 10.150.1.9 (), referer: https://alpha.spacedock.info/mod/3/Test%20download%20path/update
```
And the access.log:
```
10.150.1.9 - - [13/May/2020:21:36:13 +0000] "POST /api/mod/3/update HTTP/1.1" 400 494 "https://alpha.spacedock.info/mod/3/Test%20download%20path/update" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0"
```
(Note that despite the time indicated in the access log, the log entry is added _after_ these 15 minutes, not right in the beginning.)

I kinda suspect the traffic server to cut the connection, but I'm not sure.

**Comment by DasSkelett** [comment]
@V1TA5 has found a configuration option for the traffic server:
`proxy.config.http.transaction_active_timeout_in`
> The maximum amount of time Traffic Server can remain connected to a client. If the transfer to the client is not complete before this timeout expires, then Traffic Server closes the connection.

It was set or defaulted to 900 seconds, which equals the 15 minutes I experienced. It's now increased to one hour, which should be enough for every connection now.
I just uploaded a file for 30 minutes and it didn't cut the conenction.
