### ISSUE TITLE
Thumbnail aspect ratios

### ISSUE THREAD

**Issue by NecroBones** [KSP-SpaceDock/SpaceDock#57]
Something that always bugged me is that the aspect ratios differ for the thumbnails and banner images, even though you only upload a single image to be used for both. It was very difficult to make an image that looked good for both, especially since the centering for the thumbnail was automati (as in, it didn't center at all, it just truncated). 

Is this something folks would be interested in revisiting? I'd suggest one of several possible solutions:

1. Make them both use the same aspect ratio.

or

2. Split them out into two separate image uploads.

**Comment by sharksharkco** [comment]
Personally I never thought the banner images were utilized well on this site, I suggest removing them completely. http://i.imgur.com/JFYj180.png (also the entire grey area can be consolidated to one line) and implementing a simple gallery or encourage embedding off-site albums in the details of the mod.

This way the thumbnail can be utilized as it is.

**Comment by EIREXE** [comment]
I believe the thumbnail functionality should not be removed, it's good as it is and you still can embed stuff in the description:

http://modulous.net/mod/179/Project%20M%20Custom%20Build%20X

**Comment by sharksharkco** [comment]
I'm talking about the banner, and because you can embed in the description is part of my point. One large factor is the responsive nature of that banner, the image gets cropped/skewed/stretched depending on the screen size. That same banner in the description would probably look sharper, and would be accessible to every screen size

**Comment by NecroBones** [comment]
I'd be good with that too-- Upload a thumbnail, but eliminate the banner. 

Personally I like banner images, but it is a bit of a waste of space, often gets stretched at poor resolutions, and the modder can still embed images in the description.

**Comment by ThomasKerman** [comment]
I was already thinking about implementing a crop window for the thumbnails

**Comment by KSPSnark** [comment]
I love the thumbnails, and I love the banners, and I love that there's just one image needed to cover both of them.

The aspect ratio problem isn't purely an issue with the banners:  it happens with the thumbnails, too (they go to wide aspect ratio if you make the browser window narrow enough that three of them won't fit side-by-side).

My suggestion for a very simple fix that requires no UI changes:  just fiddle with the auto-cropping math a bit.  In particular, adjust it so that it behaves as follows:

1. Prioritize non-wrapping.  If the image is low enough that it would wrap at the top, then limit it so that the top edge of the image is in the top edge of the window.  Ditto on the bottom.  The only time that an image should ever show a "wrapping stripe" is if the whole image is so vertically narrow that you essentially have no choice but to have wrapping stripes on both top and bottom.

2. When a user does a click-drag to adjust the vertical position:  assume that the thing you want to hold constant is the vertical *center* of the image; that is, whichever point in the image is in the vertical center when the user stops dragging, try to keep that in the vertical center as the aspect ratio grows and shrinks, subject to the constraint in #1 above.  Right now it seems to zoom from the top, rather than the center, which makes it virtually impossible to pick a reasonable vertical position for the image that works well for different aspect ratios.

An enhancement to #2 above:  you could add a widget to the banner UI when the user is editing the mod.  It's a "zoom center" marker.  By default, it's in the center of the window.  In addition to dragging the image up and down, the user can also drag the zoom-center marker to place it over the spot on the image that's the most "interesting" (i.e. the bit that the user would like to stay visible if possible).  When cropping has to be done due to changing aspect ratio, the page will try to place the image so that whichever spot on the image is beneath the zoom center stays in approximately the same relative position in the window (again, subject to the wrapping constraints in #1 above).

It would be a very simple UX (drag the image so it looks the way you like it, drag the zoom marker to the spot on the image you want to focus attention on, and the latter is optional because it defaults to the center of the window.)

**Comment by V1TA5** [comment]
now its standart 16:9 but ill add a seperate thumbnail upload option.
