### ISSUE TITLE
User suggestion: galleries for mods hosted on SD

### ISSUE THREAD

**Issue by ghost** [KSP-SpaceDock/SpaceDock#64]
via support@:

> Hello, just a suggestion for spacedock, something that always frustrated me with kerbal stuff, would it be going too far to add a tab next to the info tab on mods for screenshots or something? Always love to download mods more when I can actually see them…

I'm of two minds here, as mod authors can embed Imgur galleries in the mod description. It's be a duplication of effort.

On the other hand, it does provide some convenience for users and modders, but probably not enough considering the time we would have to invest for a little used feature.

**Comment by Cionxdistan** [comment]
Well my position behind it is, even though modders can embed images in the description, Almost no one ever does. Because it's a description, not a gallery. Some barely put a description. More often than not, if I find a mod that sounds interesting on spacedock or the old Kerbal stuff, I would leave and google that mod so I could find it on another site where they had images and/or more description.

**Comment by EIREXE** [comment]
I believe that descriptions can be perfectly used, we could add imgur gallery support.

Here's a good example of a description being used as a gallery: http://modulous.net/mod/179/

**Comment by ThomasKerman** [comment]
There is Imgur Gallery support in the markdown, closing this
